---
- hosts: all
  become: true
  vars_files:
  - vars.yml
  strategy: free

  tasks:
    - name: Add the docker signing key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add the docker apt repo
      apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' state=present

    - name: Install packages
      apt:
        name: "{{ PACKAGES }}"
        state: present
        update_cache: true
        force: yes

    - name: Add user vagrant to the docker group
      user:
        name: vagrant
        groups: docker
        append: yes


    - name: Check current docker-compose version.
      command: docker-compose --version
      register: docker_compose_current_version
      changed_when: false
      failed_when: false
    
    - name: Delete existing docker-compose version if it's different.
      file:
        path: "{{ docker_compose_path }}"
        state: absent
      when: >
        docker_compose_current_version.stdout is defined
        and docker_compose_version not in docker_compose_current_version.stdout
    - name: Install Docker Compose (if configured).
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: "{{ docker_compose_path }}"
        mode: 0755
